### ISSUE TITLE
game not loading

### ISSUE THREAD

**Issue by 1bRuhN0** [trillek-team/trillek-vcomputer-module#71] opened 2021-12-07 19:28 UTC
title says it all, i don't know much about the game but that's what the thing says:
![image](https://user-images.githubusercontent.com/95714959/145093523-5db43784-9bc5-465e-9962-e91d9d592069.png)

**Comment by adam4813** [comment] 2021-12-21 01:30
This would probably be better put under https://github.com/trillek-team/tec/issues/new/choose as this repo is purely about the vcomputer module which can be used for any game/project, so I am going to close this comment here.

There is a good chance, however, that the issue is a missing assets folder. If you downloaded from a release it should be included, if you built from scratch than the README should have some documentation. If this is not the case, than can you include in the ticket you create your OS and any console output, not the in game one, but the other one.

**Closed as completed by adam4813** 2021-12-21 01:30 UTC
